language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t samueleksmo/docker-react -f Dockerfile.Dev .
    
script:
    - docker run -e CI=true USERNAME/docker-react npm run test